name: Release
on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
jobs:
  update_version:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.update.outputs.new_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - id: update
        name: Update version
        run: |
          VERSION=$(git describe --tags --abbrev=0)
          echo "Current version is $(grep '__version__' __init__.py)"

          IFS='.' read -ra VERSION_PARTS <<< "$VERSION"

          # LAST_INDEX=$(( ${#VERSION_PARTS[@]} - 1 ))
          # VERSION_PARTS[$LAST_INDEX]=$((${VERSION_PARTS[$LAST_INDEX]} + 1))

          NEW_VERSION=$(IFS=. ; echo "${VERSION_PARTS[*]}")
          echo "New version is $NEW_VERSION"

          sed -i "s/__version__ = .*/__version__ = \"$NEW_VERSION\"/g" __init__.py
          echo "New version is $(grep '__version__' __init__.py)"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

          # Update version in setup.py
          sed -i "s/version=.*/version=\"$NEW_VERSION\",/g" setup.py
          echo "New version is $(grep 'version=' setup.py)"
          
          # Commit version update
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add __init__.py setup.py
          git commit -m "Update version to $NEW_VERSION"
          git tag $NEW_VERSION
          git push origin main --follow-tags

          echo "new_version=$NEW_VERSION" >> "$GITHUB_OUTPUT"
          echo "::set-output name=new_version::$NEW_VERSION"
  build_and_publish:
    needs: update_version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          # Build package
          python setup.py sdist bdist_wheel
          
          # Publish package
          twine upload dist/*
  create_release:
    needs: [update_version, build_and_publish]
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          tag_name: ${{ needs.update_version.outputs.new_version  }}
          release_name: Release ${{ needs.update_version.outputs.new_version  }}
          draft: false
          prerelease: false
